### ISSUE TITLE
[Bug] npm install issue

### ISSUE THREAD

**Issue by Chaksack** [creativetimofficial/ct-vue-material-kit-pro#23]
### Version
1.3.0
### Reproduction link
https://github.com/Chaksack/quickteller.git
### Operating System
macos
### Device
macbook
### Browser & Version
chrome
### Steps to reproduce
npm install
### What is expected?
node module files would be installed 
### What is actually happening?
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: vue-material-kit-pro@1.3.0
npm ERR! Found: eslint@7.25.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"7.25.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@">= 1.6.0 < 7.0.0" from @vue/cli-plugin-eslint@4.5.12
npm ERR! node_modules/@vue/cli-plugin-eslint
npm ERR!   dev @vue/cli-plugin-eslint@"4.5.12" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/mac/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mac/.npm/_logs/2021-10-09T12_01_44_605Z-debug.log

---

**Comment by dragosct** [comment]
Hi, @Chaksack! Thanks for using our products. Please, be sure that you have the latest npm and nodejs LTS installed. 

Regards,
Dragos

**Comment by vscorpio** [comment]
I am also having a very hard time trying to get this up & running. It simply doesn't work. Same error.

npm install --legacy-peer-deps just throws another different error. Using a solution for that throws once again another different error and so on.

**Comment by Roni11** [comment]
Me too,
i'am using windows,

$ node -v
v16.13.1

$ npm -v
8.2.0


$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: vue-material-kit-pro@1.3.0
npm ERR! Found: eslint@7.25.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"7.25.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@">= 1.6.0 < 7.0.0" from @vue/cli-plugin-eslint@4.5.12
npm ERR! node_modules/@vue/cli-plugin-eslint
npm ERR!   dev @vue/cli-plugin-eslint@"4.5.12" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

also when using npm install --legacy-peer-deps,
$ npm install --legacy-peer-deps
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated eslint-loader@2.2.1: This loader has been deprecated. Please use eslint-webpack-plugin
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated html-webpack-plugin@3.2.0: 3.x is no longer supported
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path C:\Users\Pavilion\Documents\arnetwork-workspace\vue-material\node_modules\fibers
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node build.js || nodejs build.js
npm ERR! Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
npm ERR! C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\Pavilion\Documents\arnetwork-workspace\vue-material\node_modules\fibers\build\fibers.vcxproj]
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.13.1 | win32 | x64
npm ERR! gyp info find Python using Python version 3.10.1 found at "C:\Users\Pavilion\AppData\Local\Programs\Python\Python310\python.exe"
npm ERR! gyp info find VS using VS2015 (14.0) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio 14.0"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! (node:10224) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn C:\Users\Pavilion\AppData\Local\Programs\Python\Python310\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\Pavilion\\Documents\\arnetwork-workspace\\vue-material\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\Pavilion\\Documents\\arnetwork-workspace\\vue-material\\node_modules\\fibers\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\Pavilion\\Documents\\arnetwork-workspace\\vue-material\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\Pavilion\\AppData\\Local\\node-gyp\\Cache\\16.13.1\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Pavilion\\AppData\\Local\\node-gyp\\Cache\\16.13.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Pavilion\\Documents\\arnetwork-workspace\\vue-material\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Pavilion\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.13.1\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Pavilion\\Documents\\arnetwork-workspace\\vue-material\\node_modules\\fibers',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Users\\Pavilion\\Documents\\arnetwork-workspace\\vue-material\\node_modules\\fibers\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
npm ERR! gyp info spawn args   '/nologo',
npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (C:\Users\Pavilion\Documents\arnetwork-workspace\vue-material\node_modules\node-gyp\lib\build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19042
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Pavilion\\Documents\\arnetwork-workspace\\vue-material\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
npm ERR! gyp ERR! cwd C:\Users\Pavilion\Documents\arnetwork-workspace\vue-material\node_modules\fibers
npm ERR! gyp ERR! node -v v16.13.1
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok
npm ERR! node-gyp exited with code: 1
npm ERR! Please make sure you are using a supported platform and node version. If you
npm ERR! would like to compile fibers on this machine please make sure you have setup your
npm ERR! build environment--
npm ERR! Windows + OS X instructions here: https://github.com/nodejs/node-gyp
npm ERR! Ubuntu users please run: `sudo apt-get install g++ build-essential`
npm ERR! RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'`
npm ERR! Alpine users please run: `sudo apk add python make g++`
npm ERR! 'nodejs' is not recognized as an internal or external command,
npm ERR! operable program or batch file.



its not only this project, but all vue project cannot install,
i'am buy all of your product (8 Years Anniversary Bundle)  but all vue cannot install and can't be used,

first its say, need python3,  when i'am already installed python3, 
then its say need visual studio 2015, 
after i'am installed that, another error getting show, 
**cannot install and cannot run,**
please fix.

**Comment by dragosct** [comment]
Hi, guys! We've prepared an update for this product! Until we will put on live the update I will put the packages below in order to make the product to work with the latest nodejs version. Please run `npm install --legacy-peer-deps` and then `npm run dev`. 

```html
{
  "name": "vue-material-kit-pro",
  "author": "Creative Tim https://www.creative-tim.com/",
  "version": "1.3.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve --open",
    "dev": "npm run serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "install:clean": "rm -rf node_modules/ && rm -rf package-lock.json && npm install && npm run dev"
  },
  "dependencies": {
    "core-js": "3.12.0",
    "aos": "3.0.0-beta.6",
    "element-ui": "2.15.1",
    "google-maps": "3.3.0",
    "nouislider": "15.0.0",
    "v-tooltip": "2.1.3",
    "vue": "2.6.12",
    "vue-clickaway": "2.2.2",
    "vue-github-buttons": "3.1.0",
    "vue-lazyload": "1.3.3",
    "vue-material": "1.0.0-beta-15",
    "vue-product-zoomer": "3.0.1",
    "vue-router": "3.5.1",
    "vue2-transitions": "0.3.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "4.5.12",
    "@vue/cli-plugin-eslint": "4.5.12",
    "@vue/cli-service": "4.5.12",
    "@vue/eslint-config-prettier": "6.0.0",
    "babel-eslint": "10.1.0",
    "eslint": "7.25.0",
    "eslint-plugin-prettier": "3.4.0",
    "eslint-plugin-vue": "7.9.0",
    "prettier": "2.2.1",
    "sass": "1.32.12",
    "sass-loader": "10.1.1",
    "vue-template-compiler": "2.6.12",
    "babel-plugin-component": "1.1.1"
  }
}

```

Regards,
Dragos

**Comment by Roni11** [comment]
Still not working, 😑
Please update and put on product purchase, so i can download the update
Thank you

**Comment by sajadevo** [comment]
**Hi guys**

We've just updated the product and change the entire structure based on the latest standards, please take a look to the latest version and let us know if there is still any issue.

**All the best,**
**Sajad**
